### ISSUE TITLE
polywins error

### ISSUE THREAD

**Issue by naitik27** [Mangeshrex/dotfiles#2]
i am new to ricing, polywins throws this error https://pastebin.com/yHiGGnbT 
please tell me how to fix this.

**Comment by mngshm** [comment]
Is wmctrol and xprop installed? Can you show the screenshot of the error?

**Comment by naitik27** [comment]
> Is wmctrol and xprop installed? Can you show the screenshot of the error?

Yes wmctrl and xprop are installed

Here's the error ![Screenshot_2021-09-04_15-04-10.png](https://user-images.githubusercontent.com/57471685/132089912-867ce105-2840-4906-8c5a-f606a5f434bb.png)

**Comment by mngshm** [comment]
Bruh this is a very weird issue idk what has happened. Btw what did you do before installing or working with polywins? How did you install it?

**Comment by naitik27** [comment]
> Bruh this is a very weird issue idk what has happened. Btw what did you do before installing or working with polywins? How did you install it? 

It was just a clean system freshly installed today, it's a live boot drive I configured all your dotfiles and installed everything it needed ... Everything works except polywin, and yes I tried this on an bare metal system too but that didn't work either it gave the same error.

**Comment by mngshm** [comment]
ahh so no ideas bruh whats the issue which distro is it ?

**Comment by naitik27** [comment]
> ahh so no ideas bruh whats the issue which distro is it ? 
> 

I tried it on Kali and Ubuntu, tonight I'll give it a go on arch and see if there's any difference.

**Comment by mngshm** [comment]
hmm nice idea might work

**Comment by mngshm** [comment]
Did it get fixed on arch/arch based?

**Comment by naitik27** [comment]
> 
> 
> Did it get fixed on arch/arch based?

so i tried it in on arch and arcolinux and had no errors whatsoever, i burned the iso on my live drive again and tried it .. still didn't work i check it again on my installed operating system and it worked.

then i went a bit deeper and found out that only live systems throw this error with polywins.

so its not a problem in a script, just a live system problem

i'm closing this issue.

**Comment by mngshm** [comment]
xD lol
